# Linter Options
options:
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'src/**/*.scss'
# Rule Configuration
rules:
  brace-style: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 4
  mixins-before-declarations: 2
  nesting-depth: 0
  no-css-comments: 2
  no-ids: 2
  no-invalid-hex: 2
  no-vendor-prefixes:
    - 1
    -
      ignore-non-standard: true
  placeholder-in-extend: 0
  property-sort-order:
    - 1
    -
      order: concentric
      ignore-custom-properties: true
